# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_class_filter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_filter(object):
    def setupUi(self, add_filter):
        add_filter.setObjectName("add_filter")
        add_filter.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(add_filter)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(add_filter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(add_filter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.add_button = QtWidgets.QPushButton(add_filter)
        self.add_button.setObjectName("add_button")
        self.gridLayout.addWidget(self.add_button, 2, 1, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(add_filter)
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 2, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(add_filter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 2)
        self.comboBox = QtWidgets.QComboBox(add_filter)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 2)

        self.retranslateUi(add_filter)
        QtCore.QMetaObject.connectSlotsByName(add_filter)

    def retranslateUi(self, add_filter):
        _translate = QtCore.QCoreApplication.translate
        add_filter.setWindowTitle(_translate("add_filter", "Form"))
        self.label_2.setText(_translate("add_filter", "value:"))
        self.label.setText(_translate("add_filter", "Column:"))
        self.add_button.setText(_translate("add_filter", "Add"))
        self.cancel_button.setText(_translate("add_filter", "cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_filter = QtWidgets.QWidget()
    ui = Ui_add_filter()
    ui.setupUi(add_filter)
    add_filter.show()
    sys.exit(app.exec_())
