# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/cam_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cam_widget(object):
    def setupUi(self, cam_widget):
        cam_widget.setObjectName("cam_widget")
        cam_widget.resize(427, 337)
        cam_widget.setStyleSheet("background-color: rgb(61, 56, 70);\n"
"color: rgb(255, 255, 255);\n"
"font-family: \"Century Gothic\";\n"
"font-size:15px")
        self.gridLayout = QtWidgets.QGridLayout(cam_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.camera_label = QtWidgets.QLabel(cam_widget)
        self.camera_label.setText("")
        self.camera_label.setObjectName("camera_label")
        self.gridLayout.addWidget(self.camera_label, 0, 0, 1, 2)
        self.change_cam_button = QtWidgets.QPushButton(cam_widget)
        self.change_cam_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/cam_switch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_cam_button.setIcon(icon)
        self.change_cam_button.setIconSize(QtCore.QSize(30, 30))
        self.change_cam_button.setObjectName("change_cam_button")
        self.gridLayout.addWidget(self.change_cam_button, 1, 0, 1, 2)

        self.retranslateUi(cam_widget)
        QtCore.QMetaObject.connectSlotsByName(cam_widget)

    def retranslateUi(self, cam_widget):
        _translate = QtCore.QCoreApplication.translate
        cam_widget.setWindowTitle(_translate("cam_widget", "Form"))
        self.change_cam_button.setText(_translate("cam_widget", "Change camera"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cam_widget = QtWidgets.QWidget()
    ui = Ui_cam_widget()
    ui.setupUi(cam_widget)
    cam_widget.show()
    sys.exit(app.exec_())
