# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/classroom_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_classroom_list(object):
    def setupUi(self, classroom_list):
        classroom_list.setObjectName("classroom_list")
        classroom_list.resize(620, 570)
        classroom_list.setStyleSheet("background-color: rgb(61, 56, 70);\n"
"color: rgb(255, 255, 255);\n"
"font-family: \"Century Gothic\";\n"
"font-size:15px")
        self.gridLayout = QtWidgets.QGridLayout(classroom_list)
        self.gridLayout.setObjectName("gridLayout")
        self.classroom_table = QtWidgets.QTableView(classroom_list)
        self.classroom_table.setStyleSheet("QTableView {\n"
"    background-color: #333;\n"
"    gridline-color: #444;\n"
"    color: #fff;\n"
"    selection-background-color: #555;\n"
"}\n"
"\n"
"/* Set the background color and text color of the header section */\n"
"QHeaderView::section {\n"
"    background-color: #444;\n"
"    color: #fff;\n"
"    padding: 4px;\n"
"    border: 1px solid #555;\n"
"}\n"
"\n"
"/* Set the sort indicator arrow color */\n"
"QHeaderView::down-arrow, QHeaderView::up-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    image: url();\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    image: url(down_arrow_white.png);\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    image: url(up_arrow_white.png);\n"
"}\n"
"\n"
"/* Set the selection color for individual cells */\n"
"QTableView::item:selected {\n"
"    background-color: #666;\n"
"    color: #fff;\n"
"}\n"
"\n"
"/* Set the hover color for individual cells */\n"
"QTableView::item:hover {\n"
"    background-color: #555;\n"
"    color: #fff;\n"
"}\n"
"\n"
"/* Set the border around the table */\n"
"QTableView::item {\n"
"    border: 1px solid #444;\n"
"}\n"
"\n"
"/* Set the alternate row color */\n"
"QTableView::item:alternate {\n"
"    background-color: #444;\n"
"}\n"
"\n"
"/* Remove the focus rectangle around cells */\n"
"QTableView:focus {\n"
"    outline: none;\n"
"}")
        self.classroom_table.setObjectName("classroom_table")
        self.classroom_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.classroom_table, 0, 1, 4, 1)
        self.add_button = QtWidgets.QToolButton(classroom_list)
        self.add_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon)
        self.add_button.setIconSize(QtCore.QSize(30, 30))
        self.add_button.setObjectName("add_button")
        self.gridLayout.addWidget(self.add_button, 0, 0, 1, 1)
        self.delete_button = QtWidgets.QToolButton(classroom_list)
        self.delete_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/delete_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon1)
        self.delete_button.setIconSize(QtCore.QSize(30, 30))
        self.delete_button.setObjectName("delete_button")
        self.gridLayout.addWidget(self.delete_button, 1, 0, 1, 1)

        self.retranslateUi(classroom_list)
        QtCore.QMetaObject.connectSlotsByName(classroom_list)

    def retranslateUi(self, classroom_list):
        _translate = QtCore.QCoreApplication.translate
        classroom_list.setWindowTitle(_translate("classroom_list", "Form"))
        self.add_button.setText(_translate("classroom_list", "..."))
        self.delete_button.setText(_translate("classroom_list", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    classroom_list = QtWidgets.QWidget()
    ui = Ui_classroom_list()
    ui.setupUi(classroom_list)
    classroom_list.show()
    sys.exit(app.exec_())
