# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/class_edit_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_class_edit_form(object):
    def setupUi(self, class_edit_form):
        class_edit_form.setObjectName("class_edit_form")
        class_edit_form.resize(749, 982)
        class_edit_form.setStyleSheet("background-color: rgb(61, 56, 70);\n"
"color: rgb(255, 255, 255);\n"
"font-family: \"Century Gothic\";\n"
"font-size:20px")
        self.gridLayout = QtWidgets.QGridLayout(class_edit_form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(class_edit_form)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 1, 1, 1)
        self.save_button = QtWidgets.QPushButton(class_edit_form)
        self.save_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button.setIcon(icon)
        self.save_button.setIconSize(QtCore.QSize(30, 30))
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 13, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(class_edit_form)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 12, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(class_edit_form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        self.end_time_input = QtWidgets.QTimeEdit(class_edit_form)
        self.end_time_input.setObjectName("end_time_input")
        self.gridLayout.addWidget(self.end_time_input, 7, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(class_edit_form)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(class_edit_form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(class_edit_form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.start_time_input = QtWidgets.QTimeEdit(class_edit_form)
        self.start_time_input.setObjectName("start_time_input")
        self.gridLayout.addWidget(self.start_time_input, 6, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(class_edit_form)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 11, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(class_edit_form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(class_edit_form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(class_edit_form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(class_edit_form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(class_edit_form)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 10, 1, 1, 1)
        self.Cancel_button = QtWidgets.QPushButton(class_edit_form)
        self.Cancel_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cancel_button.setIcon(icon1)
        self.Cancel_button.setIconSize(QtCore.QSize(30, 30))
        self.Cancel_button.setObjectName("Cancel_button")
        self.gridLayout.addWidget(self.Cancel_button, 13, 4, 1, 1)
        self.salary_input = QtWidgets.QLineEdit(class_edit_form)
        self.salary_input.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.salary_input.setObjectName("salary_input")
        self.gridLayout.addWidget(self.salary_input, 12, 3, 1, 2)
        self.teachers_payement_combobox = QtWidgets.QComboBox(class_edit_form)
        self.teachers_payement_combobox.setObjectName("teachers_payement_combobox")
        self.gridLayout.addWidget(self.teachers_payement_combobox, 11, 3, 1, 2)
        self.session_price_input = QtWidgets.QLineEdit(class_edit_form)
        self.session_price_input.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.session_price_input.setObjectName("session_price_input")
        self.gridLayout.addWidget(self.session_price_input, 10, 3, 1, 2)
        self.price_input = QtWidgets.QLineEdit(class_edit_form)
        self.price_input.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.price_input.setObjectName("price_input")
        self.gridLayout.addWidget(self.price_input, 8, 3, 1, 2)
        self.day_combobox = QtWidgets.QComboBox(class_edit_form)
        self.day_combobox.setObjectName("day_combobox")
        self.gridLayout.addWidget(self.day_combobox, 5, 3, 1, 2)
        self.classroom_combobox = QtWidgets.QComboBox(class_edit_form)
        self.classroom_combobox.setObjectName("classroom_combobox")
        self.gridLayout.addWidget(self.classroom_combobox, 4, 3, 1, 2)
        self.teacher_combobox = QtWidgets.QComboBox(class_edit_form)
        self.teacher_combobox.setObjectName("teacher_combobox")
        self.gridLayout.addWidget(self.teacher_combobox, 3, 3, 1, 2)
        self.subject_combobox = QtWidgets.QComboBox(class_edit_form)
        self.subject_combobox.setObjectName("subject_combobox")
        self.gridLayout.addWidget(self.subject_combobox, 2, 3, 1, 2)
        self.year_combobox = QtWidgets.QComboBox(class_edit_form)
        self.year_combobox.setObjectName("year_combobox")
        self.gridLayout.addWidget(self.year_combobox, 1, 3, 1, 2)
        self.level_combobox = QtWidgets.QComboBox(class_edit_form)
        self.level_combobox.setObjectName("level_combobox")
        self.gridLayout.addWidget(self.level_combobox, 0, 3, 1, 2)

        self.retranslateUi(class_edit_form)
        QtCore.QMetaObject.connectSlotsByName(class_edit_form)

    def retranslateUi(self, class_edit_form):
        _translate = QtCore.QCoreApplication.translate
        class_edit_form.setWindowTitle(_translate("class_edit_form", "Form"))
        self.label_9.setText(_translate("class_edit_form", "Monthly Price"))
        self.save_button.setText(_translate("class_edit_form", " Save"))
        self.label_11.setText(_translate("class_edit_form", "Salary:"))
        self.label_5.setText(_translate("class_edit_form", "Day:"))
        self.label_8.setText(_translate("class_edit_form", "Year:"))
        self.label_2.setText(_translate("class_edit_form", "Subject:"))
        self.label_3.setText(_translate("class_edit_form", "Teacher:"))
        self.label_10.setText(_translate("class_edit_form", "Teacher\'s payement:"))
        self.label_4.setText(_translate("class_edit_form", "Classroom:"))
        self.label_7.setText(_translate("class_edit_form", "End time:"))
        self.label_6.setText(_translate("class_edit_form", "Start time:"))
        self.label.setText(_translate("class_edit_form", "Level:"))
        self.label_12.setText(_translate("class_edit_form", "Session Price"))
        self.Cancel_button.setText(_translate("class_edit_form", " Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    class_edit_form = QtWidgets.QWidget()
    ui = Ui_class_edit_form()
    ui.setupUi(class_edit_form)
    class_edit_form.show()
    sys.exit(app.exec_())
