# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/class_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_classCard(object):
    def setupUi(self, classCard):
        classCard.setObjectName("classCard")
        classCard.resize(1160, 679)
        classCard.setStyleSheet("background-color:rgb(61, 56, 70);\n"
"color:black;\n"
"font-size:15px")
        self.gridLayout = QtWidgets.QGridLayout(classCard)
        self.gridLayout.setObjectName("gridLayout")
        self.tabs = QtWidgets.QTabWidget(classCard)
        self.tabs.setStyleSheet("\n"
"QTabWidget {\n"
"    background-color: rgb(70, 34, 67); /* Set the background color of the tab widget */\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: ; /* Set the text color of the tab */\n"
"    padding: 8px 12px;\n"
"    background-color: rgb(119, 118, 123);\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(222, 221, 218); /* Set the background color of the selected tab */\n"
"    color: rgb(0, 0, 0); /* Set the text color of the selected tab */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0)\n"
"}\n"
"\n"
"")
        self.tabs.setIconSize(QtCore.QSize(30, 30))
        self.tabs.setObjectName("tabs")
        self.info_tab = QtWidgets.QWidget()
        self.info_tab.setObjectName("info_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.info_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.info_stacked_widget = QtWidgets.QStackedWidget(self.info_tab)
        self.info_stacked_widget.setObjectName("info_stacked_widget")
        self.info_widget = QtWidgets.QWidget()
        self.info_widget.setObjectName("info_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.info_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.register_attendance_button = QtWidgets.QPushButton(self.info_widget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.register_attendance_button.setFont(font)
        self.register_attendance_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Simple_red_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.register_attendance_button.setIcon(icon)
        self.register_attendance_button.setIconSize(QtCore.QSize(16, 16))
        self.register_attendance_button.setObjectName("register_attendance_button")
        self.gridLayout_3.addWidget(self.register_attendance_button, 5, 3, 1, 1)
        self.widget = QtWidgets.QWidget(self.info_widget)
        self.widget.setStyleSheet("background-color:rgb(119, 118, 123);\n"
"color:white;\n"
"")
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.info_layout = QtWidgets.QVBoxLayout()
        self.info_layout.setObjectName("info_layout")
        self.gridLayout_4.addLayout(self.info_layout, 0, 1, 1, 1)
        self.labels_layout = QtWidgets.QVBoxLayout()
        self.labels_layout.setObjectName("labels_layout")
        self.gridLayout_4.addLayout(self.labels_layout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 2, 2, 2, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.info_widget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 1)
        self.info_stacked_widget.addWidget(self.info_widget)
        self.camera_widget = QtWidgets.QWidget()
        self.camera_widget.setObjectName("camera_widget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.camera_widget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.registration_table = QtWidgets.QTableView(self.camera_widget)
        self.registration_table.setStyleSheet("color:black;\n"
"background-color: rgb(255, 255, 255);")
        self.registration_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.registration_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.registration_table.setObjectName("registration_table")
        self.gridLayout_11.addWidget(self.registration_table, 0, 3, 3, 1)
        self.video_label = QtWidgets.QLabel(self.camera_widget)
        self.video_label.setStyleSheet("background-color:black;")
        self.video_label.setObjectName("video_label")
        self.gridLayout_11.addWidget(self.video_label, 0, 0, 1, 2)
        self.stop_registration_button = QtWidgets.QPushButton(self.camera_widget)
        self.stop_registration_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"    \n"
"    color: rgb(192, 191, 188);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/stoprec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_registration_button.setIcon(icon1)
        self.stop_registration_button.setIconSize(QtCore.QSize(30, 30))
        self.stop_registration_button.setObjectName("stop_registration_button")
        self.gridLayout_11.addWidget(self.stop_registration_button, 1, 0, 1, 1)
        self.change_cam_button = QtWidgets.QPushButton(self.camera_widget)
        self.change_cam_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"    \n"
"    color: rgb(192, 191, 188);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/cam_switch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_cam_button.setIcon(icon2)
        self.change_cam_button.setIconSize(QtCore.QSize(30, 30))
        self.change_cam_button.setObjectName("change_cam_button")
        self.gridLayout_11.addWidget(self.change_cam_button, 1, 1, 1, 1)
        self.info_stacked_widget.addWidget(self.camera_widget)
        self.gridLayout_2.addWidget(self.info_stacked_widget, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.info_tab, icon3, "")
        self.students_tab = QtWidgets.QWidget()
        self.students_tab.setObjectName("students_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.students_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.class_student_stackedwidget = QtWidgets.QStackedWidget(self.students_tab)
        self.class_student_stackedwidget.setEnabled(True)
        self.class_student_stackedwidget.setObjectName("class_student_stackedwidget")
        self.class_students_widget = QtWidgets.QWidget()
        self.class_students_widget.setObjectName("class_students_widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.class_students_widget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.payement_button = QtWidgets.QPushButton(self.class_students_widget)
        self.payement_button.setEnabled(False)
        self.payement_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/payment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.payement_button.setIcon(icon4)
        self.payement_button.setIconSize(QtCore.QSize(30, 30))
        self.payement_button.setObjectName("payement_button")
        self.gridLayout_6.addWidget(self.payement_button, 6, 1, 1, 1)
        self.add_student_button = QtWidgets.QToolButton(self.class_students_widget)
        self.add_student_button.setEnabled(True)
        self.add_student_button.setStyleSheet("QToolButton {\n"
"    background-color:rgb(61, 56, 70)\n"
"\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_student_button.setIcon(icon5)
        self.add_student_button.setIconSize(QtCore.QSize(30, 30))
        self.add_student_button.setObjectName("add_student_button")
        self.gridLayout_6.addWidget(self.add_student_button, 0, 0, 1, 1)
        self.show_all_button = QtWidgets.QToolButton(self.class_students_widget)
        self.show_all_button.setEnabled(True)
        self.show_all_button.setStyleSheet("QToolButton {\n"
"    background-color:rgb(61, 56, 70)\n"
"\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/showall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_all_button.setIcon(icon6)
        self.show_all_button.setIconSize(QtCore.QSize(30, 30))
        self.show_all_button.setObjectName("show_all_button")
        self.gridLayout_6.addWidget(self.show_all_button, 2, 0, 1, 1)
        self.unpaid_students_button = QtWidgets.QPushButton(self.class_students_widget)
        self.unpaid_students_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/unpaid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unpaid_students_button.setIcon(icon7)
        self.unpaid_students_button.setIconSize(QtCore.QSize(30, 30))
        self.unpaid_students_button.setObjectName("unpaid_students_button")
        self.gridLayout_6.addWidget(self.unpaid_students_button, 6, 3, 1, 1)
        self.delete_student_button = QtWidgets.QToolButton(self.class_students_widget)
        self.delete_student_button.setEnabled(False)
        self.delete_student_button.setStyleSheet("QToolButton {\n"
"    background-color:rgb(61, 56, 70)\n"
"\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/delete_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_student_button.setIcon(icon8)
        self.delete_student_button.setIconSize(QtCore.QSize(30, 30))
        self.delete_student_button.setObjectName("delete_student_button")
        self.gridLayout_6.addWidget(self.delete_student_button, 1, 0, 1, 1)
        self.paid_students_button = QtWidgets.QPushButton(self.class_students_widget)
        self.paid_students_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/paid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.paid_students_button.setIcon(icon9)
        self.paid_students_button.setIconSize(QtCore.QSize(30, 30))
        self.paid_students_button.setObjectName("paid_students_button")
        self.gridLayout_6.addWidget(self.paid_students_button, 6, 2, 1, 1)
        self.classstudents_table = QtWidgets.QTableView(self.class_students_widget)
        self.classstudents_table.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black;")
        self.classstudents_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.classstudents_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.classstudents_table.setObjectName("classstudents_table")
        self.classstudents_table.horizontalHeader().setDefaultSectionSize(500)
        self.gridLayout_6.addWidget(self.classstudents_table, 0, 1, 6, 3)
        self.class_student_stackedwidget.addWidget(self.class_students_widget)
        self.add_student_widget = QtWidgets.QWidget()
        self.add_student_widget.setObjectName("add_student_widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.add_student_widget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.cancel_button = QtWidgets.QPushButton(self.add_student_widget)
        self.cancel_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_button.setIcon(icon10)
        self.cancel_button.setIconSize(QtCore.QSize(30, 30))
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout_7.addWidget(self.cancel_button, 3, 1, 1, 1)
        self.search_input = QtWidgets.QLineEdit(self.add_student_widget)
        self.search_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.search_input.setObjectName("search_input")
        self.gridLayout_7.addWidget(self.search_input, 0, 0, 1, 2)
        self.student_table = QtWidgets.QTableView(self.add_student_widget)
        self.student_table.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black")
        self.student_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.student_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.student_table.setObjectName("student_table")
        self.student_table.horizontalHeader().setDefaultSectionSize(500)
        self.gridLayout_7.addWidget(self.student_table, 0, 3, 3, 1)
        self.search_button = QtWidgets.QPushButton(self.add_student_widget)
        self.search_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon11)
        self.search_button.setObjectName("search_button")
        self.gridLayout_7.addWidget(self.search_button, 1, 0, 1, 2)
        self.ok_button = QtWidgets.QPushButton(self.add_student_widget)
        self.ok_button.setEnabled(False)
        self.ok_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ok_button.setIcon(icon12)
        self.ok_button.setIconSize(QtCore.QSize(30, 30))
        self.ok_button.setObjectName("ok_button")
        self.gridLayout_7.addWidget(self.ok_button, 3, 0, 1, 1)
        self.class_student_stackedwidget.addWidget(self.add_student_widget)
        self.payement_widget = QtWidgets.QWidget()
        self.payement_widget.setObjectName("payement_widget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.payement_widget)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.return_button_2 = QtWidgets.QPushButton(self.payement_widget)
        self.return_button_2.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.return_button_2.setIcon(icon13)
        self.return_button_2.setObjectName("return_button_2")
        self.gridLayout_12.addWidget(self.return_button_2, 0, 0, 1, 1)
        self.payement_tableview = QtWidgets.QTableView(self.payement_widget)
        self.payement_tableview.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.payement_tableview.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.payement_tableview.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.payement_tableview.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.payement_tableview.setObjectName("payement_tableview")
        self.payement_tableview.horizontalHeader().setCascadingSectionResizes(True)
        self.payement_tableview.horizontalHeader().setDefaultSectionSize(250)
        self.payement_tableview.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_12.addWidget(self.payement_tableview, 0, 1, 1, 1)
        self.class_student_stackedwidget.addWidget(self.payement_widget)
        self.gridLayout_5.addWidget(self.class_student_stackedwidget, 0, 0, 1, 1)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/students.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.students_tab, icon14, "")
        self.records_tab = QtWidgets.QWidget()
        self.records_tab.setObjectName("records_tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.records_tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.records_stackedwidget = QtWidgets.QStackedWidget(self.records_tab)
        self.records_stackedwidget.setObjectName("records_stackedwidget")
        self.record_widget = QtWidgets.QWidget()
        self.record_widget.setObjectName("record_widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.record_widget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.record_table = QtWidgets.QTableView(self.record_widget)
        self.record_table.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:black")
        self.record_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.record_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.record_table.setObjectName("record_table")
        self.record_table.horizontalHeader().setDefaultSectionSize(500)
        self.record_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.record_table, 0, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 2, 2, 1, 1)
        self.Attendance_button = QtWidgets.QPushButton(self.record_widget)
        self.Attendance_button.setEnabled(False)
        self.Attendance_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"    \n"
"    color: rgb(192, 191, 188);\n"
"}\n"
"")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/attendance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Attendance_button.setIcon(icon15)
        self.Attendance_button.setIconSize(QtCore.QSize(30, 30))
        self.Attendance_button.setObjectName("Attendance_button")
        self.gridLayout_8.addWidget(self.Attendance_button, 1, 0, 1, 1)
        self.delete_record_button = QtWidgets.QPushButton(self.record_widget)
        self.delete_record_button.setEnabled(False)
        self.delete_record_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"    \n"
"    color: rgb(192, 191, 188);\n"
"}\n"
"")
        self.delete_record_button.setIcon(icon8)
        self.delete_record_button.setIconSize(QtCore.QSize(30, 30))
        self.delete_record_button.setObjectName("delete_record_button")
        self.gridLayout_8.addWidget(self.delete_record_button, 1, 1, 1, 1)
        self.delete_all_button = QtWidgets.QPushButton(self.record_widget)
        self.delete_all_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/delete_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_all_button.setIcon(icon16)
        self.delete_all_button.setIconSize(QtCore.QSize(30, 30))
        self.delete_all_button.setObjectName("delete_all_button")
        self.gridLayout_8.addWidget(self.delete_all_button, 1, 2, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.record_widget)
        self.calendarWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_8.addWidget(self.calendarWidget, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 2, 0, 1, 1)
        self.records_stackedwidget.addWidget(self.record_widget)
        self.attendance_widget = QtWidgets.QWidget()
        self.attendance_widget.setObjectName("attendance_widget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.attendance_widget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.return_button = QtWidgets.QPushButton(self.attendance_widget)
        self.return_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        self.return_button.setIcon(icon13)
        self.return_button.setObjectName("return_button")
        self.gridLayout_10.addWidget(self.return_button, 0, 0, 1, 1)
        self.attendance_table = QtWidgets.QTableView(self.attendance_widget)
        self.attendance_table.setStyleSheet("background-color:  rgb(255, 255, 255);")
        self.attendance_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.attendance_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.attendance_table.setObjectName("attendance_table")
        self.attendance_table.horizontalHeader().setDefaultSectionSize(500)
        self.attendance_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_10.addWidget(self.attendance_table, 0, 1, 1, 1)
        self.records_stackedwidget.addWidget(self.attendance_widget)
        self.gridLayout_9.addWidget(self.records_stackedwidget, 0, 0, 1, 1)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/records.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.records_tab, icon17, "")
        self.gridLayout.addWidget(self.tabs, 0, 0, 1, 1)

        self.retranslateUi(classCard)
        self.tabs.setCurrentIndex(0)
        self.info_stacked_widget.setCurrentIndex(0)
        self.class_student_stackedwidget.setCurrentIndex(1)
        self.records_stackedwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(classCard)

    def retranslateUi(self, classCard):
        _translate = QtCore.QCoreApplication.translate
        classCard.setWindowTitle(_translate("classCard", "Form"))
        self.register_attendance_button.setText(_translate("classCard", "Register attendance"))
        self.label.setText(_translate("classCard", "Class Info:"))
        self.video_label.setText(_translate("classCard", "TextLabel"))
        self.stop_registration_button.setText(_translate("classCard", " Stop"))
        self.change_cam_button.setText(_translate("classCard", " Change Cam"))
        self.tabs.setTabText(self.tabs.indexOf(self.info_tab), _translate("classCard", "Info"))
        self.payement_button.setText(_translate("classCard", " Payement"))
        self.add_student_button.setText(_translate("classCard", "..."))
        self.show_all_button.setText(_translate("classCard", "..."))
        self.unpaid_students_button.setText(_translate("classCard", "Unpaid Students"))
        self.delete_student_button.setText(_translate("classCard", "..."))
        self.paid_students_button.setText(_translate("classCard", "Paid Students"))
        self.cancel_button.setText(_translate("classCard", " cancel"))
        self.search_button.setText(_translate("classCard", " Search"))
        self.ok_button.setText(_translate("classCard", " Ok"))
        self.return_button_2.setText(_translate("classCard", "return"))
        self.tabs.setTabText(self.tabs.indexOf(self.students_tab), _translate("classCard", "Students"))
        self.Attendance_button.setText(_translate("classCard", "Attendance"))
        self.delete_record_button.setText(_translate("classCard", "Delete"))
        self.delete_all_button.setText(_translate("classCard", " Delete all"))
        self.return_button.setText(_translate("classCard", "Return"))
        self.tabs.setTabText(self.tabs.indexOf(self.records_tab), _translate("classCard", "Records"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    classCard = QtWidgets.QWidget()
    ui = Ui_classCard()
    ui.setupUi(classCard)
    classCard.show()
    sys.exit(app.exec_())
