# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1170, 913)
        MainWindow.setStyleSheet("\n"
"QWidget{\n"
"background-color: rgb(36, 31, 49);\n"
"color:white;\n"
"font-size:15px;\n"
"font-family: \"Century Gothic\";\n"
"\n"
"}\n"
"\n"
"            QToolButton {\n"
"                background-color: #007BFF;\n"
"                color: white;\n"
"                border: none;\n"
"                padding: 8px 16px;\n"
"                border-radius: 4px;\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color: rgb(246, 245, 244);\n"
"            }\n"
"QToolButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(153, 193, 241);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QTableView {\n"
"    background-color: transparent; /* Make the background transparent */\n"
"    border: 1px solid #CCCCCC; /* Add a subtle border */\n"
"    border-radius: 10px; /* Round the corners */\n"
"    gridline-color: transparent; /* Make grid lines transparent */\n"
"    selection-background-color: #007ACC; /* Selection background color */\n"
"    selection-color: #FFFFFF; /* Selection text color */\n"
"    alternate-background-color: #F0F0F0; /* Alternate row background color */\n"
"    box-shadow: 0px 2px 8px rgba(0, 0, 0, 0.2); /* Add shadow */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"      font-weight: bold;\n"
"    background-color: rgb(36, 31, 49);\n"
"    color: rgb(255, 255, 255); /* Header text color */\n"
"    padding: 6px; /* Add padding to header sections */\n"
"    border: none; /* Remove border */\n"
"    border-radius: 5px; /* Round the header corners */\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 8px; /* Add padding to table items */\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none; /* Remove vertical scroll bar border */\n"
"    background: #F0F0F0; /* Scroll bar background color */\n"
"    width: 10px; /* Scroll bar width */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #007ACC; /* Scroll bar handle color */\n"
"    min-height: 20px; /* Scroll bar handle minimum height */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none; /* Remove scroll bar buttons background */\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setStyleSheet("QTabBar::tab:hover {\n"
"    background-color:  rgb(68, 132, 233);\n"
"    color:rgb(0, 0, 0)\n"
"}\n"
"            QTabWidget::pane {\n"
"                border: 1px solid #ccc;\n"
"                background-color: white;\n"
"            }\n"
"            QTabWidget::tab-bar {\n"
"                alignment: center;\n"
"            }\n"
"            QTabBar::tab {\n"
"                background: rgb(255, 255, 255);\n"
"                color: #333;\n"
"                border: 1px solid #ccc;\n"
"                border-top-left-radius: 4px;\n"
"                border-top-right-radius: 4px;\n"
"                padding: 8px;\n"
"                min-width: 100px;\n"
"            }\n"
"            QTabBar::tab:selected {\n"
"                background:rgba(238, 233, 233, 155);\n"
"                border-bottom-color: white;\n"
"            }\n"
"\n"
"")
        self.tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabs.setIconSize(QtCore.QSize(30, 30))
        self.tabs.setObjectName("tabs")
        self.classes_tab = QtWidgets.QWidget()
        self.classes_tab.setStyleSheet("QPushButton {\n"
"    background-color: purple;\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8A2BE2;  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4B0082;  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #D3D3D3; /* Change the disabled color as desired */\n"
"    color: #A9A9A9; /* Change the disabled text color as desired */\n"
"}")
        self.classes_tab.setObjectName("classes_tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.classes_tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.classe_table = QtWidgets.QTableView(self.classes_tab)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setKerning(False)
        self.classe_table.setFont(font)
        self.classe_table.setStyleSheet("")
        self.classe_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.classe_table.setFrameShadow(QtWidgets.QFrame.Raised)
        self.classe_table.setLineWidth(1)
        self.classe_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.classe_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.classe_table.setShowGrid(True)
        self.classe_table.setGridStyle(QtCore.Qt.SolidLine)
        self.classe_table.setObjectName("classe_table")
        self.classe_table.horizontalHeader().setDefaultSectionSize(250)
        self.classe_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.classe_table, 0, 1, 12, 3)
        self.delete_class_button = QtWidgets.QToolButton(self.classes_tab)
        self.delete_class_button.setEnabled(False)
        self.delete_class_button.setStyleSheet("            QToolButton{\n"
"                background-color: rgb(237, 51, 59)\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color: rgb(192, 28, 40)\n"
"            }\n"
"QToolButton:pressed {\n"
"    background-color: rgb(246, 97, 81);  /* Change the pressed color as desired */\n"
"}\n"
"QToolButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI/ui/../../icons/delete_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_class_button.setIcon(icon)
        self.delete_class_button.setIconSize(QtCore.QSize(30, 30))
        self.delete_class_button.setObjectName("delete_class_button")
        self.gridLayout_8.addWidget(self.delete_class_button, 1, 0, 1, 1)
        self.open_class_button = QtWidgets.QToolButton(self.classes_tab)
        self.open_class_button.setEnabled(False)
        self.open_class_button.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI/ui/../../icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_class_button.setIcon(icon1)
        self.open_class_button.setIconSize(QtCore.QSize(30, 30))
        self.open_class_button.setObjectName("open_class_button")
        self.gridLayout_8.addWidget(self.open_class_button, 2, 0, 1, 1)
        self.edit_class_button = QtWidgets.QToolButton(self.classes_tab)
        self.edit_class_button.setEnabled(False)
        self.edit_class_button.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("UI/ui/../../icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_class_button.setIcon(icon2)
        self.edit_class_button.setIconSize(QtCore.QSize(30, 30))
        self.edit_class_button.setObjectName("edit_class_button")
        self.gridLayout_8.addWidget(self.edit_class_button, 5, 0, 1, 1)
        self.today_classes_button = QtWidgets.QToolButton(self.classes_tab)
        self.today_classes_button.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("UI/ui/../../icons/today_class.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.today_classes_button.setIcon(icon3)
        self.today_classes_button.setIconSize(QtCore.QSize(30, 30))
        self.today_classes_button.setObjectName("today_classes_button")
        self.gridLayout_8.addWidget(self.today_classes_button, 8, 0, 1, 1)
        self.time_management_button = QtWidgets.QToolButton(self.classes_tab)
        self.time_management_button.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("UI/ui/../../icons/time_management.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.time_management_button.setIcon(icon4)
        self.time_management_button.setIconSize(QtCore.QSize(30, 30))
        self.time_management_button.setObjectName("time_management_button")
        self.gridLayout_8.addWidget(self.time_management_button, 7, 0, 1, 1)
        self.add_class_button = QtWidgets.QToolButton(self.classes_tab)
        self.add_class_button.setEnabled(True)
        self.add_class_button.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("UI/ui/../../icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_class_button.setIcon(icon5)
        self.add_class_button.setIconSize(QtCore.QSize(30, 30))
        self.add_class_button.setObjectName("add_class_button")
        self.gridLayout_8.addWidget(self.add_class_button, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.classes_tab)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-size: 20px")
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 12, 2, 1, 1)
        self.show_all_classes_button = QtWidgets.QToolButton(self.classes_tab)
        self.show_all_classes_button.setEnabled(True)
        self.show_all_classes_button.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("UI/ui/../../icons/showall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_all_classes_button.setIcon(icon6)
        self.show_all_classes_button.setIconSize(QtCore.QSize(30, 30))
        self.show_all_classes_button.setObjectName("show_all_classes_button")
        self.gridLayout_8.addWidget(self.show_all_classes_button, 6, 0, 1, 1)
        self.subjects_button = QtWidgets.QToolButton(self.classes_tab)
        self.subjects_button.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("UI/ui/../../icons/subjects.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.subjects_button.setIcon(icon7)
        self.subjects_button.setIconSize(QtCore.QSize(30, 30))
        self.subjects_button.setObjectName("subjects_button")
        self.gridLayout_8.addWidget(self.subjects_button, 9, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 16, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(35, 450, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 11, 0, 6, 1)
        self.classroom_button = QtWidgets.QToolButton(self.classes_tab)
        self.classroom_button.setStyleSheet("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("UI/ui/../../icons/classroom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.classroom_button.setIcon(icon8)
        self.classroom_button.setIconSize(QtCore.QSize(30, 30))
        self.classroom_button.setObjectName("classroom_button")
        self.gridLayout_8.addWidget(self.classroom_button, 10, 0, 1, 1)
        self.filter_table = QtWidgets.QTableView(self.classes_tab)
        self.filter_table.setStyleSheet("")
        self.filter_table.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.filter_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.filter_table.setObjectName("filter_table")
        self.filter_table.horizontalHeader().setDefaultSectionSize(200)
        self.filter_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.filter_table, 13, 2, 4, 1)
        self.remove_filter_button = QtWidgets.QToolButton(self.classes_tab)
        self.remove_filter_button.setStyleSheet("            QToolButton{\n"
"                background-color: rgb(237, 51, 59)\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color: rgb(246, 245, 244)\n"
"            }\n"
"QToolButton:pressed {\n"
"    background-color: rgb(246, 97, 81);  /* Change the pressed color as desired */\n"
"}\n"
"QToolButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        self.remove_filter_button.setIcon(icon)
        self.remove_filter_button.setIconSize(QtCore.QSize(30, 30))
        self.remove_filter_button.setObjectName("remove_filter_button")
        self.gridLayout_8.addWidget(self.remove_filter_button, 13, 3, 1, 1)
        self.filter_button = QtWidgets.QToolButton(self.classes_tab)
        self.filter_button.setStyleSheet("")
        self.filter_button.setIcon(icon5)
        self.filter_button.setIconSize(QtCore.QSize(30, 30))
        self.filter_button.setObjectName("filter_button")
        self.gridLayout_8.addWidget(self.filter_button, 14, 3, 1, 1)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("UI/ui/../../icons/class.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.classes_tab, icon9, "")
        self.teachers_tab = QtWidgets.QWidget()
        self.teachers_tab.setObjectName("teachers_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.teachers_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.teacher_stackedwidget = QtWidgets.QStackedWidget(self.teachers_tab)
        self.teacher_stackedwidget.setObjectName("teacher_stackedwidget")
        self.teachers_list_widget = QtWidgets.QWidget()
        self.teachers_list_widget.setObjectName("teachers_list_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.teachers_list_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.search_teacher_input = QtWidgets.QLineEdit(self.teachers_list_widget)
        self.search_teacher_input.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.search_teacher_input.setObjectName("search_teacher_input")
        self.gridLayout_2.addWidget(self.search_teacher_input, 2, 1, 1, 1)
        self.search_teacher_button = QtWidgets.QToolButton(self.teachers_list_widget)
        self.search_teacher_button.setStyleSheet("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("UI/ui/../../icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_teacher_button.setIcon(icon10)
        self.search_teacher_button.setIconSize(QtCore.QSize(30, 30))
        self.search_teacher_button.setObjectName("search_teacher_button")
        self.gridLayout_2.addWidget(self.search_teacher_button, 2, 2, 1, 1)
        self.teachers_table = QtWidgets.QTableView(self.teachers_list_widget)
        self.teachers_table.setStyleSheet("")
        self.teachers_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.teachers_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.teachers_table.setObjectName("teachers_table")
        self.teachers_table.horizontalHeader().setSortIndicatorShown(False)
        self.teachers_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.teachers_table, 3, 1, 11, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 3, 1, 1)
        self.delete_teacher_button = QtWidgets.QToolButton(self.teachers_list_widget)
        self.delete_teacher_button.setEnabled(False)
        self.delete_teacher_button.setStyleSheet("            QToolButton{\n"
"                background-color: rgb(237, 51, 59)\n"
"            }\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgb(246, 97, 81);  /* Change the pressed color as desired */\n"
"}\n"
"QToolButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(246, 245, 244); /* Change the disabled color as desired */\n"
"}")
        self.delete_teacher_button.setIcon(icon)
        self.delete_teacher_button.setIconSize(QtCore.QSize(30, 30))
        self.delete_teacher_button.setObjectName("delete_teacher_button")
        self.gridLayout_2.addWidget(self.delete_teacher_button, 3, 0, 1, 1)
        self.add_teacher_button = QtWidgets.QToolButton(self.teachers_list_widget)
        self.add_teacher_button.setEnabled(True)
        self.add_teacher_button.setStyleSheet("")
        self.add_teacher_button.setIcon(icon5)
        self.add_teacher_button.setIconSize(QtCore.QSize(30, 30))
        self.add_teacher_button.setObjectName("add_teacher_button")
        self.gridLayout_2.addWidget(self.add_teacher_button, 4, 0, 1, 1)
        self.open_teacher_button = QtWidgets.QToolButton(self.teachers_list_widget)
        self.open_teacher_button.setEnabled(False)
        self.open_teacher_button.setStyleSheet("")
        self.open_teacher_button.setIcon(icon1)
        self.open_teacher_button.setIconSize(QtCore.QSize(30, 30))
        self.open_teacher_button.setObjectName("open_teacher_button")
        self.gridLayout_2.addWidget(self.open_teacher_button, 5, 0, 1, 1)
        self.edit_teacher_button = QtWidgets.QToolButton(self.teachers_list_widget)
        self.edit_teacher_button.setEnabled(False)
        self.edit_teacher_button.setStyleSheet("")
        self.edit_teacher_button.setIcon(icon2)
        self.edit_teacher_button.setIconSize(QtCore.QSize(30, 30))
        self.edit_teacher_button.setObjectName("edit_teacher_button")
        self.gridLayout_2.addWidget(self.edit_teacher_button, 6, 0, 1, 1)
        self.show_all_button = QtWidgets.QToolButton(self.teachers_list_widget)
        self.show_all_button.setStyleSheet("")
        self.show_all_button.setIcon(icon6)
        self.show_all_button.setIconSize(QtCore.QSize(30, 30))
        self.show_all_button.setObjectName("show_all_button")
        self.gridLayout_2.addWidget(self.show_all_button, 7, 0, 1, 1)
        self.info_teacher_button = QtWidgets.QToolButton(self.teachers_list_widget)
        self.info_teacher_button.setStyleSheet("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("UI/ui/../../icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info_teacher_button.setIcon(icon11)
        self.info_teacher_button.setIconSize(QtCore.QSize(30, 30))
        self.info_teacher_button.setObjectName("info_teacher_button")
        self.gridLayout_2.addWidget(self.info_teacher_button, 8, 0, 1, 1)
        self.teacher_stackedwidget.addWidget(self.teachers_list_widget)
        self.teachers_info_widget = QtWidgets.QWidget()
        self.teachers_info_widget.setObjectName("teachers_info_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.teachers_info_widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.teachers_info_widget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font-size: 20px")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.teachers_info_widget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size: 20px")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.teachers_info_widget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-size: 20px")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.teacher_reaturn_button = QtWidgets.QPushButton(self.teachers_info_widget)
        self.teacher_reaturn_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("UI/ui/../../icons/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.teacher_reaturn_button.setIcon(icon12)
        self.teacher_reaturn_button.setIconSize(QtCore.QSize(30, 30))
        self.teacher_reaturn_button.setObjectName("teacher_reaturn_button")
        self.gridLayout_4.addWidget(self.teacher_reaturn_button, 7, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 7, 1, 1, 1)
        self.high_layout = QtWidgets.QHBoxLayout()
        self.high_layout.setObjectName("high_layout")
        self.gridLayout_4.addLayout(self.high_layout, 5, 0, 1, 2)
        self.middle_layout = QtWidgets.QHBoxLayout()
        self.middle_layout.setObjectName("middle_layout")
        self.gridLayout_4.addLayout(self.middle_layout, 3, 0, 1, 2)
        self.elementry_layout = QtWidgets.QHBoxLayout()
        self.elementry_layout.setObjectName("elementry_layout")
        self.gridLayout_4.addLayout(self.elementry_layout, 1, 0, 1, 2)
        self.teacher_stackedwidget.addWidget(self.teachers_info_widget)
        self.gridLayout.addWidget(self.teacher_stackedwidget, 0, 0, 1, 1)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("UI/ui/../../icons/teacher.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.teachers_tab, icon13, "")
        self.student_tab = QtWidgets.QWidget()
        self.student_tab.setObjectName("student_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.student_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 3, 1, 1)
        self.open_student_button = QtWidgets.QToolButton(self.student_tab)
        self.open_student_button.setEnabled(False)
        self.open_student_button.setStyleSheet("")
        self.open_student_button.setIcon(icon1)
        self.open_student_button.setIconSize(QtCore.QSize(30, 30))
        self.open_student_button.setObjectName("open_student_button")
        self.gridLayout_5.addWidget(self.open_student_button, 2, 0, 1, 1)
        self.add_student_button = QtWidgets.QToolButton(self.student_tab)
        self.add_student_button.setEnabled(True)
        self.add_student_button.setStyleSheet("")
        self.add_student_button.setIcon(icon5)
        self.add_student_button.setIconSize(QtCore.QSize(30, 30))
        self.add_student_button.setObjectName("add_student_button")
        self.gridLayout_5.addWidget(self.add_student_button, 3, 0, 1, 1)
        self.search_student_input = QtWidgets.QLineEdit(self.student_tab)
        self.search_student_input.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.search_student_input.setObjectName("search_student_input")
        self.gridLayout_5.addWidget(self.search_student_input, 0, 1, 1, 1)
        self.search_student_button = QtWidgets.QToolButton(self.student_tab)
        self.search_student_button.setStyleSheet("")
        self.search_student_button.setIcon(icon10)
        self.search_student_button.setIconSize(QtCore.QSize(30, 30))
        self.search_student_button.setObjectName("search_student_button")
        self.gridLayout_5.addWidget(self.search_student_button, 0, 2, 1, 1)
        self.delete_student_button = QtWidgets.QToolButton(self.student_tab)
        self.delete_student_button.setEnabled(False)
        self.delete_student_button.setStyleSheet("            QToolButton{\n"
"                background-color: rgb(237, 51, 59)\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color: rgb(246, 245, 244)\n"
"            }\n"
"QToolButton:pressed {\n"
"    background-color: rgb(246, 97, 81);  /* Change the pressed color as desired */\n"
"}\n"
"QToolButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        self.delete_student_button.setIcon(icon)
        self.delete_student_button.setIconSize(QtCore.QSize(30, 30))
        self.delete_student_button.setObjectName("delete_student_button")
        self.gridLayout_5.addWidget(self.delete_student_button, 1, 0, 1, 1)
        self.students_table = QtWidgets.QTableView(self.student_tab)
        self.students_table.setStyleSheet("")
        self.students_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.students_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.students_table.setObjectName("students_table")
        self.students_table.horizontalHeader().setCascadingSectionResizes(True)
        self.students_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_5.addWidget(self.students_table, 1, 1, 8, 3)
        self.edit_student_button = QtWidgets.QToolButton(self.student_tab)
        self.edit_student_button.setEnabled(False)
        self.edit_student_button.setStyleSheet("")
        self.edit_student_button.setIcon(icon2)
        self.edit_student_button.setIconSize(QtCore.QSize(30, 30))
        self.edit_student_button.setObjectName("edit_student_button")
        self.gridLayout_5.addWidget(self.edit_student_button, 4, 0, 1, 1)
        self.show_all_students_button = QtWidgets.QToolButton(self.student_tab)
        self.show_all_students_button.setStyleSheet("")
        self.show_all_students_button.setIcon(icon6)
        self.show_all_students_button.setIconSize(QtCore.QSize(30, 30))
        self.show_all_students_button.setObjectName("show_all_students_button")
        self.gridLayout_5.addWidget(self.show_all_students_button, 5, 0, 1, 1)
        self.find_by_id_button = QtWidgets.QToolButton(self.student_tab)
        self.find_by_id_button.setStyleSheet("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("UI/ui/../../icons/qrsearch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.find_by_id_button.setIcon(icon14)
        self.find_by_id_button.setIconSize(QtCore.QSize(30, 30))
        self.find_by_id_button.setObjectName("find_by_id_button")
        self.gridLayout_5.addWidget(self.find_by_id_button, 6, 0, 1, 1)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("UI/ui/../../icons/students.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.student_tab, icon15, "")
        self.users_tab = QtWidgets.QWidget()
        self.users_tab.setObjectName("users_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.users_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.users_tableView = QtWidgets.QTableView(self.users_tab)
        self.users_tableView.setStyleSheet("")
        self.users_tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.users_tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.users_tableView.setObjectName("users_tableView")
        self.users_tableView.horizontalHeader().setDefaultSectionSize(100)
        self.users_tableView.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.users_tableView, 1, 5, 6, 1)
        self.delete_user_button = QtWidgets.QToolButton(self.users_tab)
        self.delete_user_button.setEnabled(False)
        self.delete_user_button.setStyleSheet("            QToolButton{\n"
"                background-color: rgb(237, 51, 59)\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color:rgb(246, 245, 244)\n"
"            }\n"
"QToolButton:pressed {\n"
"    background-color: rgb(246, 97, 81);  /* Change the pressed color as desired */\n"
"}\n"
"QToolButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        self.delete_user_button.setIcon(icon)
        self.delete_user_button.setIconSize(QtCore.QSize(30, 30))
        self.delete_user_button.setObjectName("delete_user_button")
        self.gridLayout_6.addWidget(self.delete_user_button, 1, 2, 1, 1)
        self.add_user_button = QtWidgets.QToolButton(self.users_tab)
        self.add_user_button.setEnabled(True)
        self.add_user_button.setStyleSheet("")
        self.add_user_button.setIcon(icon5)
        self.add_user_button.setIconSize(QtCore.QSize(30, 30))
        self.add_user_button.setObjectName("add_user_button")
        self.gridLayout_6.addWidget(self.add_user_button, 2, 2, 1, 1)
        self.edit_user_button = QtWidgets.QToolButton(self.users_tab)
        self.edit_user_button.setEnabled(False)
        self.edit_user_button.setStyleSheet("")
        self.edit_user_button.setIcon(icon2)
        self.edit_user_button.setIconSize(QtCore.QSize(30, 30))
        self.edit_user_button.setObjectName("edit_user_button")
        self.gridLayout_6.addWidget(self.edit_user_button, 3, 2, 1, 1)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("UI/ui/../../icons/person.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.users_tab, icon16, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab)
        self.calendarWidget.setEnabled(True)
        self.calendarWidget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font-size: 14px")
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_7.addWidget(self.calendarWidget, 13, 6, 6, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 568, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 6, 14, 1, 1)
        self.with_button = QtWidgets.QToolButton(self.tab)
        self.with_button.setEnabled(False)
        self.with_button.setStyleSheet("")
        self.with_button.setIcon(icon16)
        self.with_button.setIconSize(QtCore.QSize(30, 30))
        self.with_button.setObjectName("with_button")
        self.gridLayout_7.addWidget(self.with_button, 2, 0, 1, 1)
        self.showall_payment_button = QtWidgets.QToolButton(self.tab)
        self.showall_payment_button.setEnabled(True)
        self.showall_payment_button.setStyleSheet("")
        self.showall_payment_button.setIcon(icon6)
        self.showall_payment_button.setIconSize(QtCore.QSize(30, 30))
        self.showall_payment_button.setObjectName("showall_payment_button")
        self.gridLayout_7.addWidget(self.showall_payment_button, 0, 0, 1, 1)
        self.payment_tableview = QtWidgets.QTableView(self.tab)
        self.payment_tableview.setStyleSheet("")
        self.payment_tableview.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.payment_tableview.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.payment_tableview.setObjectName("payment_tableview")
        self.payment_tableview.horizontalHeader().setCascadingSectionResizes(True)
        self.payment_tableview.horizontalHeader().setSortIndicatorShown(False)
        self.payment_tableview.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.payment_tableview, 0, 1, 10, 13)
        self.month_radioButton = QtWidgets.QRadioButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.month_radioButton.setFont(font)
        self.month_radioButton.setChecked(True)
        self.month_radioButton.setObjectName("month_radioButton")
        self.gridLayout_7.addWidget(self.month_radioButton, 11, 6, 1, 1)
        self.day_radioButton = QtWidgets.QRadioButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.day_radioButton.setFont(font)
        self.day_radioButton.setObjectName("day_radioButton")
        self.gridLayout_7.addWidget(self.day_radioButton, 11, 7, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem6, 11, 8, 1, 1)
        self.filterpayment_combobox = QtWidgets.QComboBox(self.tab)
        self.filterpayment_combobox.setObjectName("filterpayment_combobox")
        self.gridLayout_7.addWidget(self.filterpayment_combobox, 11, 9, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 11, 10, 1, 1)
        self.profit_label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.profit_label.setFont(font)
        self.profit_label.setText("")
        self.profit_label.setObjectName("profit_label")
        self.gridLayout_7.addWidget(self.profit_label, 11, 12, 1, 1)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("UI/ui/../../icons/payment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.tab, icon17, "")
        self.gridLayout_3.addWidget(self.tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        self.teacher_stackedwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.delete_class_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">delete class</span></p></body></html>"))
        self.delete_class_button.setText(_translate("MainWindow", "..."))
        self.open_class_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">show info</span></p></body></html>"))
        self.open_class_button.setWhatsThis(_translate("MainWindow", "open class"))
        self.open_class_button.setText(_translate("MainWindow", "..."))
        self.edit_class_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">edit class</span></p></body></html>"))
        self.edit_class_button.setText(_translate("MainWindow", "..."))
        self.today_classes_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">today classes</span></p></body></html>"))
        self.today_classes_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Todat\'s classes</p></body></html>"))
        self.today_classes_button.setText(_translate("MainWindow", "..."))
        self.time_management_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">time mangement</span></p></body></html>"))
        self.time_management_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>time management</p></body></html>"))
        self.time_management_button.setText(_translate("MainWindow", "..."))
        self.add_class_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">add class</span></p></body></html>"))
        self.add_class_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>add class</p></body></html>"))
        self.add_class_button.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Apply filters:"))
        self.show_all_classes_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">show all classes</span></p></body></html>"))
        self.show_all_classes_button.setText(_translate("MainWindow", "..."))
        self.subjects_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">subjects</span></p></body></html>"))
        self.subjects_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>subjects</p><p><br/></p></body></html>"))
        self.subjects_button.setText(_translate("MainWindow", "..."))
        self.classroom_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">classrooms</span></p></body></html>"))
        self.classroom_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>classrooms</p><p><br/></p></body></html>"))
        self.classroom_button.setText(_translate("MainWindow", "..."))
        self.remove_filter_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">delete filter</span></p></body></html>"))
        self.remove_filter_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>remove class filter</p><p><br/></p></body></html>"))
        self.remove_filter_button.setText(_translate("MainWindow", "..."))
        self.filter_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">add filter</span></p></body></html>"))
        self.filter_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>add class filter</p><p><br/></p></body></html>"))
        self.filter_button.setText(_translate("MainWindow", "..."))
        self.tabs.setTabText(self.tabs.indexOf(self.classes_tab), _translate("MainWindow", "Classes"))
        self.search_teacher_input.setPlaceholderText(_translate("MainWindow", "search teacher..."))
        self.search_teacher_button.setText(_translate("MainWindow", "..."))
        self.delete_teacher_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">delete teacher</span></p></body></html>"))
        self.delete_teacher_button.setText(_translate("MainWindow", "..."))
        self.add_teacher_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">add teacher</span></p></body></html>"))
        self.add_teacher_button.setText(_translate("MainWindow", "..."))
        self.open_teacher_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">show info</span></p></body></html>"))
        self.open_teacher_button.setText(_translate("MainWindow", "..."))
        self.edit_teacher_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">edit teacher</span></p></body></html>"))
        self.edit_teacher_button.setText(_translate("MainWindow", "..."))
        self.show_all_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">show all</span></p></body></html>"))
        self.show_all_button.setText(_translate("MainWindow", "..."))
        self.info_teacher_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">info </span></p></body></html>"))
        self.info_teacher_button.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "High school:"))
        self.label.setText(_translate("MainWindow", "Elementry school:"))
        self.label_2.setText(_translate("MainWindow", "Middle school:"))
        self.teacher_reaturn_button.setText(_translate("MainWindow", " Return"))
        self.tabs.setTabText(self.tabs.indexOf(self.teachers_tab), _translate("MainWindow", "Teachers List"))
        self.open_student_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">show info</span></p><p><br/></p></body></html>"))
        self.open_student_button.setText(_translate("MainWindow", "..."))
        self.add_student_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">add student</span></p></body></html>"))
        self.add_student_button.setText(_translate("MainWindow", "..."))
        self.search_student_input.setPlaceholderText(_translate("MainWindow", "search student..."))
        self.search_student_button.setText(_translate("MainWindow", "..."))
        self.delete_student_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">delete student</span></p></body></html>"))
        self.delete_student_button.setText(_translate("MainWindow", "..."))
        self.edit_student_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">edit student</span></p></body></html>"))
        self.edit_student_button.setText(_translate("MainWindow", "..."))
        self.show_all_students_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">show all</span></p></body></html>"))
        self.show_all_students_button.setText(_translate("MainWindow", "..."))
        self.find_by_id_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">find by id</span></p></body></html>"))
        self.find_by_id_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>find by Qr code</p></body></html>"))
        self.find_by_id_button.setText(_translate("MainWindow", "..."))
        self.tabs.setTabText(self.tabs.indexOf(self.student_tab), _translate("MainWindow", "Students List"))
        self.delete_user_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">delete user</span></p></body></html>"))
        self.delete_user_button.setText(_translate("MainWindow", "..."))
        self.add_user_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">add user</span></p></body></html>"))
        self.add_user_button.setText(_translate("MainWindow", "..."))
        self.edit_user_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">edit user</span></p></body></html>"))
        self.edit_user_button.setText(_translate("MainWindow", "..."))
        self.tabs.setTabText(self.tabs.indexOf(self.users_tab), _translate("MainWindow", "Users"))
        self.with_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">payer/payee info</span></p></body></html>"))
        self.with_button.setText(_translate("MainWindow", "..."))
        self.showall_payment_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#00007f;\">show all</span></p></body></html>"))
        self.showall_payment_button.setText(_translate("MainWindow", "..."))
        self.month_radioButton.setText(_translate("MainWindow", "by month"))
        self.day_radioButton.setText(_translate("MainWindow", "by day"))
        self.label_6.setText(_translate("MainWindow", "Total:"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("MainWindow", "Payment"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
