# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/student_add_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_student_add_form(object):
    def setupUi(self, student_add_form):
        student_add_form.setObjectName("student_add_form")
        student_add_form.resize(682, 669)
        student_add_form.setStyleSheet("background-color: rgb(61, 56, 70);\n"
"color: rgb(255, 255, 255);\n"
"font-family: \"Century Gothic\";\n"
"font-size:15px")
        self.gridLayout = QtWidgets.QGridLayout(student_add_form)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(student_add_form)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.firstname_input = QtWidgets.QLineEdit(self.page)
        self.firstname_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.firstname_input.setObjectName("firstname_input")
        self.gridLayout_2.addWidget(self.firstname_input, 0, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.phone_input = QtWidgets.QLineEdit(self.page)
        self.phone_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.phone_input.setObjectName("phone_input")
        self.gridLayout_2.addWidget(self.phone_input, 2, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.take_photo_button = QtWidgets.QPushButton(self.page)
        self.take_photo_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/cam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.take_photo_button.setIcon(icon)
        self.take_photo_button.setIconSize(QtCore.QSize(30, 30))
        self.take_photo_button.setObjectName("take_photo_button")
        self.gridLayout_2.addWidget(self.take_photo_button, 4, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lastname_input = QtWidgets.QLineEdit(self.page)
        self.lastname_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lastname_input.setObjectName("lastname_input")
        self.gridLayout_2.addWidget(self.lastname_input, 1, 1, 1, 2)
        self.Cancel_button = QtWidgets.QPushButton(self.page)
        self.Cancel_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cancel_button.setIcon(icon1)
        self.Cancel_button.setIconSize(QtCore.QSize(30, 30))
        self.Cancel_button.setObjectName("Cancel_button")
        self.gridLayout_2.addWidget(self.Cancel_button, 6, 2, 1, 1)
        self.add_button = QtWidgets.QPushButton(self.page)
        self.add_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon2)
        self.add_button.setIconSize(QtCore.QSize(30, 30))
        self.add_button.setObjectName("add_button")
        self.gridLayout_2.addWidget(self.add_button, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.email_input = QtWidgets.QLineEdit(self.page)
        self.email_input.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.email_input.setObjectName("email_input")
        self.gridLayout_2.addWidget(self.email_input, 3, 1, 1, 2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.take_button = QtWidgets.QPushButton(self.page_2)
        self.take_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/take.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.take_button.setIcon(icon3)
        self.take_button.setIconSize(QtCore.QSize(30, 30))
        self.take_button.setObjectName("take_button")
        self.gridLayout_3.addWidget(self.take_button, 1, 0, 1, 1)
        self.change_cam_button = QtWidgets.QPushButton(self.page_2)
        self.change_cam_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/cam_switch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_cam_button.setIcon(icon4)
        self.change_cam_button.setIconSize(QtCore.QSize(30, 30))
        self.change_cam_button.setObjectName("change_cam_button")
        self.gridLayout_3.addWidget(self.change_cam_button, 1, 1, 1, 1)
        self.camera_label = QtWidgets.QLabel(self.page_2)
        self.camera_label.setText("")
        self.camera_label.setObjectName("camera_label")
        self.gridLayout_3.addWidget(self.camera_label, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(student_add_form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(student_add_form)

    def retranslateUi(self, student_add_form):
        _translate = QtCore.QCoreApplication.translate
        student_add_form.setWindowTitle(_translate("student_add_form", "Form"))
        self.label_3.setText(_translate("student_add_form", "Phone:"))
        self.label_2.setText(_translate("student_add_form", "Last name:"))
        self.take_photo_button.setText(_translate("student_add_form", " Take a photo"))
        self.label.setText(_translate("student_add_form", "First name:"))
        self.Cancel_button.setText(_translate("student_add_form", " Cancel"))
        self.add_button.setText(_translate("student_add_form", " Add"))
        self.label_4.setText(_translate("student_add_form", "Email:"))
        self.take_button.setText(_translate("student_add_form", " Capture"))
        self.change_cam_button.setText(_translate("student_add_form", "Change camera"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    student_add_form = QtWidgets.QWidget()
    ui = Ui_student_add_form()
    ui.setupUi(student_add_form)
    student_add_form.show()
    sys.exit(app.exec_())
