# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/student_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StudentCard(object):
    def setupUi(self, StudentCard):
        StudentCard.setObjectName("StudentCard")
        StudentCard.resize(1091, 807)
        StudentCard.setStyleSheet("background-color:rgb(61, 56, 70);\n"
"color:white;\n"
"font-size:15px;\n"
"font-family: \"Century Gothic\";\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(StudentCard)
        self.gridLayout.setObjectName("gridLayout")
        self.tabs = QtWidgets.QTabWidget(StudentCard)
        self.tabs.setStyleSheet("\n"
"QTabWidget {\n"
"    background-color: rgb(70, 34, 67); /* Set the background color of the tab widget */\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: ; /* Set the text color of the tab */\n"
"    padding: 8px 12px;\n"
"    background-color: rgb(119, 118, 123);\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(222, 221, 218); /* Set the background color of the selected tab */\n"
"    color: rgb(0, 0, 0); /* Set the text color of the selected tab */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0)\n"
"}\n"
"\n"
"")
        self.tabs.setObjectName("tabs")
        self.info = QtWidgets.QWidget()
        self.info.setObjectName("info")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.info)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget = QtWidgets.QWidget(self.info)
        self.widget.setStyleSheet("background-color:rgb(119, 118, 123)")
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.info_layout = QtWidgets.QVBoxLayout()
        self.info_layout.setObjectName("info_layout")
        self.gridLayout_4.addLayout(self.info_layout, 0, 1, 1, 1)
        self.labels_layout = QtWidgets.QVBoxLayout()
        self.labels_layout.setObjectName("labels_layout")
        self.gridLayout_4.addLayout(self.labels_layout, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.widget, 2, 0, 2, 1)
        self.qr_code_label = QtWidgets.QLabel(self.info)
        self.qr_code_label.setText("")
        self.qr_code_label.setObjectName("qr_code_label")
        self.gridLayout_8.addWidget(self.qr_code_label, 0, 2, 1, 1)
        self.view_button = QtWidgets.QPushButton(self.info)
        self.view_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/QR.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_button.setIcon(icon)
        self.view_button.setIconSize(QtCore.QSize(30, 30))
        self.view_button.setObjectName("view_button")
        self.gridLayout_8.addWidget(self.view_button, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.info)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 1, 0, 1, 1)
        self.tabs.addTab(self.info, "")
        self.classes_tab = QtWidgets.QWidget()
        self.classes_tab.setObjectName("classes_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.classes_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.info_stacked_widget = QtWidgets.QStackedWidget(self.classes_tab)
        self.info_stacked_widget.setStyleSheet("")
        self.info_stacked_widget.setObjectName("info_stacked_widget")
        self.info_widget = QtWidgets.QWidget()
        self.info_widget.setObjectName("info_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.info_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.info_widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.add_class_button = QtWidgets.QPushButton(self.info_widget)
        self.add_class_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_class_button.setIcon(icon1)
        self.add_class_button.setIconSize(QtCore.QSize(30, 30))
        self.add_class_button.setObjectName("add_class_button")
        self.gridLayout_3.addWidget(self.add_class_button, 3, 0, 1, 2)
        self.student_class_table = QtWidgets.QTableView(self.info_widget)
        self.student_class_table.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:rgb(11, 11, 11)")
        self.student_class_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.student_class_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.student_class_table.setObjectName("student_class_table")
        self.student_class_table.horizontalHeader().setDefaultSectionSize(270)
        self.gridLayout_3.addWidget(self.student_class_table, 2, 0, 1, 6)
        self.delete_class_button = QtWidgets.QPushButton(self.info_widget)
        self.delete_class_button.setEnabled(False)
        self.delete_class_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/delete_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_class_button.setIcon(icon2)
        self.delete_class_button.setIconSize(QtCore.QSize(30, 30))
        self.delete_class_button.setObjectName("delete_class_button")
        self.gridLayout_3.addWidget(self.delete_class_button, 3, 2, 1, 2)
        self.class_payement_button = QtWidgets.QPushButton(self.info_widget)
        self.class_payement_button.setEnabled(False)
        self.class_payement_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/payment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.class_payement_button.setIcon(icon3)
        self.class_payement_button.setIconSize(QtCore.QSize(30, 30))
        self.class_payement_button.setObjectName("class_payement_button")
        self.gridLayout_3.addWidget(self.class_payement_button, 3, 4, 1, 2)
        self.info_stacked_widget.addWidget(self.info_widget)
        self.add_class_widget = QtWidgets.QWidget()
        self.add_class_widget.setObjectName("add_class_widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.add_class_widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.search_input = QtWidgets.QLineEdit(self.add_class_widget)
        self.search_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.search_input.setObjectName("search_input")
        self.gridLayout_5.addWidget(self.search_input, 0, 0, 1, 2)
        self.cancel_button = QtWidgets.QPushButton(self.add_class_widget)
        self.cancel_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_button.setIcon(icon4)
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout_5.addWidget(self.cancel_button, 3, 1, 1, 1)
        self.ok_button = QtWidgets.QPushButton(self.add_class_widget)
        self.ok_button.setEnabled(False)
        self.ok_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ok_button.setIcon(icon5)
        self.ok_button.setObjectName("ok_button")
        self.gridLayout_5.addWidget(self.ok_button, 3, 0, 1, 1)
        self.classes_table = QtWidgets.QTableView(self.add_class_widget)
        self.classes_table.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.classes_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.classes_table.setObjectName("classes_table")
        self.classes_table.horizontalHeader().setDefaultSectionSize(270)
        self.gridLayout_5.addWidget(self.classes_table, 0, 2, 4, 1)
        self.search_button = QtWidgets.QPushButton(self.add_class_widget)
        self.search_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon6)
        self.search_button.setIconSize(QtCore.QSize(30, 30))
        self.search_button.setObjectName("search_button")
        self.gridLayout_5.addWidget(self.search_button, 1, 0, 1, 1)
        self.info_stacked_widget.addWidget(self.add_class_widget)
        self.class_payement_widget = QtWidgets.QWidget()
        self.class_payement_widget.setObjectName("class_payement_widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.class_payement_widget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.return_button = QtWidgets.QPushButton(self.class_payement_widget)
        self.return_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.return_button.setIcon(icon7)
        self.return_button.setIconSize(QtCore.QSize(30, 30))
        self.return_button.setObjectName("return_button")
        self.gridLayout_6.addWidget(self.return_button, 2, 0, 1, 1)
        self.class_payement_tableview = QtWidgets.QTableView(self.class_payement_widget)
        self.class_payement_tableview.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.class_payement_tableview.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.class_payement_tableview.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.class_payement_tableview.setObjectName("class_payement_tableview")
        self.gridLayout_6.addWidget(self.class_payement_tableview, 0, 2, 3, 1)
        self.payement_stackedWidget = QtWidgets.QStackedWidget(self.class_payement_widget)
        self.payement_stackedWidget.setObjectName("payement_stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.update_payement_button = QtWidgets.QPushButton(self.page)
        self.update_payement_button.setEnabled(True)
        self.update_payement_button.setGeometry(QtCore.QRect(0, 160, 516, 68))
        self.update_payement_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/records.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.update_payement_button.setIcon(icon8)
        self.update_payement_button.setIconSize(QtCore.QSize(30, 30))
        self.update_payement_button.setObjectName("update_payement_button")
        self.payement_stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.update_button = QtWidgets.QPushButton(self.page_2)
        self.update_button.setEnabled(False)
        self.update_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        self.update_button.setIcon(icon5)
        self.update_button.setIconSize(QtCore.QSize(30, 30))
        self.update_button.setObjectName("update_button")
        self.gridLayout_7.addWidget(self.update_button, 5, 0, 1, 1)
        self.cancelupdate_button = QtWidgets.QPushButton(self.page_2)
        self.cancelupdate_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        self.cancelupdate_button.setIcon(icon4)
        self.cancelupdate_button.setIconSize(QtCore.QSize(30, 30))
        self.cancelupdate_button.setObjectName("cancelupdate_button")
        self.gridLayout_7.addWidget(self.cancelupdate_button, 5, 1, 1, 1)
        self.by_month = QtWidgets.QRadioButton(self.page_2)
        self.by_month.setStyleSheet("")
        self.by_month.setChecked(True)
        self.by_month.setObjectName("by_month")
        self.gridLayout_7.addWidget(self.by_month, 2, 0, 1, 2)
        self.by_session = QtWidgets.QRadioButton(self.page_2)
        self.by_session.setStyleSheet("")
        self.by_session.setObjectName("by_session")
        self.gridLayout_7.addWidget(self.by_session, 1, 0, 1, 2)
        self.value_input = QtWidgets.QLineEdit(self.page_2)
        self.value_input.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.value_input.setObjectName("value_input")
        self.gridLayout_7.addWidget(self.value_input, 0, 0, 1, 2)
        self.generate_bill_checkbox = QtWidgets.QCheckBox(self.page_2)
        self.generate_bill_checkbox.setChecked(True)
        self.generate_bill_checkbox.setObjectName("generate_bill_checkbox")
        self.gridLayout_7.addWidget(self.generate_bill_checkbox, 6, 0, 1, 1)
        self.payement_stackedWidget.addWidget(self.page_2)
        self.gridLayout_6.addWidget(self.payement_stackedWidget, 0, 0, 1, 1)
        self.info_stacked_widget.addWidget(self.class_payement_widget)
        self.gridLayout_2.addWidget(self.info_stacked_widget, 0, 0, 1, 1)
        self.tabs.addTab(self.classes_tab, "")
        self.gridLayout.addWidget(self.tabs, 0, 0, 1, 1)

        self.retranslateUi(StudentCard)
        self.tabs.setCurrentIndex(0)
        self.info_stacked_widget.setCurrentIndex(0)
        self.payement_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(StudentCard)

    def retranslateUi(self, StudentCard):
        _translate = QtCore.QCoreApplication.translate
        StudentCard.setWindowTitle(_translate("StudentCard", "Form"))
        self.view_button.setText(_translate("StudentCard", "generate Qr code"))
        self.label.setText(_translate("StudentCard", "Student info:"))
        self.tabs.setTabText(self.tabs.indexOf(self.info), _translate("StudentCard", "Info"))
        self.label_2.setText(_translate("StudentCard", "Student classes:"))
        self.add_class_button.setText(_translate("StudentCard", " Add"))
        self.delete_class_button.setText(_translate("StudentCard", " Delete"))
        self.class_payement_button.setText(_translate("StudentCard", " class payement"))
        self.cancel_button.setText(_translate("StudentCard", "Cancel"))
        self.ok_button.setText(_translate("StudentCard", "Ok"))
        self.search_button.setText(_translate("StudentCard", "Search"))
        self.return_button.setText(_translate("StudentCard", " return"))
        self.update_payement_button.setText(_translate("StudentCard", "update payement"))
        self.update_button.setText(_translate("StudentCard", " update"))
        self.cancelupdate_button.setText(_translate("StudentCard", " cancel"))
        self.by_month.setText(_translate("StudentCard", "by month"))
        self.by_session.setText(_translate("StudentCard", "by session"))
        self.generate_bill_checkbox.setText(_translate("StudentCard", "generate bill"))
        self.tabs.setTabText(self.tabs.indexOf(self.classes_tab), _translate("StudentCard", "Classes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StudentCard = QtWidgets.QWidget()
    ui = Ui_StudentCard()
    ui.setupUi(StudentCard)
    StudentCard.show()
    sys.exit(app.exec_())
