# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/student_edit_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_student_edit_form(object):
    def setupUi(self, student_edit_form):
        student_edit_form.setObjectName("student_edit_form")
        student_edit_form.resize(749, 669)
        student_edit_form.setStyleSheet("background-color: rgb(61, 56, 70);\n"
"color: rgb(255, 255, 255);\n"
"font-family: \"Century Gothic\";\n"
"font-size:15px")
        self.gridLayout = QtWidgets.QGridLayout(student_edit_form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(student_edit_form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.firstname_input = QtWidgets.QLineEdit(student_edit_form)
        self.firstname_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.firstname_input.setObjectName("firstname_input")
        self.gridLayout.addWidget(self.firstname_input, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(student_edit_form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lastname_input = QtWidgets.QLineEdit(student_edit_form)
        self.lastname_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lastname_input.setObjectName("lastname_input")
        self.gridLayout.addWidget(self.lastname_input, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(student_edit_form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.phone_input = QtWidgets.QLineEdit(student_edit_form)
        self.phone_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.phone_input.setObjectName("phone_input")
        self.gridLayout.addWidget(self.phone_input, 2, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(student_edit_form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.email_input = QtWidgets.QLineEdit(student_edit_form)
        self.email_input.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.email_input.setObjectName("email_input")
        self.gridLayout.addWidget(self.email_input, 3, 1, 1, 2)
        self.save_button = QtWidgets.QPushButton(student_edit_form)
        self.save_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button.setIcon(icon)
        self.save_button.setIconSize(QtCore.QSize(30, 30))
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 4, 1, 1, 1)
        self.Cancel_button = QtWidgets.QPushButton(student_edit_form)
        self.Cancel_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cancel_button.setIcon(icon1)
        self.Cancel_button.setIconSize(QtCore.QSize(30, 30))
        self.Cancel_button.setObjectName("Cancel_button")
        self.gridLayout.addWidget(self.Cancel_button, 4, 2, 1, 1)

        self.retranslateUi(student_edit_form)
        QtCore.QMetaObject.connectSlotsByName(student_edit_form)

    def retranslateUi(self, student_edit_form):
        _translate = QtCore.QCoreApplication.translate
        student_edit_form.setWindowTitle(_translate("student_edit_form", "Form"))
        self.label.setText(_translate("student_edit_form", "First name:"))
        self.label_2.setText(_translate("student_edit_form", "Last name:"))
        self.label_3.setText(_translate("student_edit_form", "Phone:"))
        self.label_4.setText(_translate("student_edit_form", "Email:"))
        self.save_button.setText(_translate("student_edit_form", " Save"))
        self.Cancel_button.setText(_translate("student_edit_form", " Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    student_edit_form = QtWidgets.QWidget()
    ui = Ui_student_edit_form()
    ui.setupUi(student_edit_form)
    student_edit_form.show()
    sys.exit(app.exec_())
