# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/teacher_add_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_teacher_add_form(object):
    def setupUi(self, teacher_add_form):
        teacher_add_form.setObjectName("teacher_add_form")
        teacher_add_form.resize(749, 669)
        teacher_add_form.setStyleSheet("background-color: rgb(61, 56, 70);\n"
"color:white;\n"
"font-family: \"Century Gothic\";\n"
"font-size:15px\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(teacher_add_form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(teacher_add_form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.firstname_input = QtWidgets.QLineEdit(teacher_add_form)
        self.firstname_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.firstname_input.setObjectName("firstname_input")
        self.gridLayout.addWidget(self.firstname_input, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(teacher_add_form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lastname_input = QtWidgets.QLineEdit(teacher_add_form)
        self.lastname_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lastname_input.setObjectName("lastname_input")
        self.gridLayout.addWidget(self.lastname_input, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(teacher_add_form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.subject_comboBox = QtWidgets.QComboBox(teacher_add_form)
        self.subject_comboBox.setObjectName("subject_comboBox")
        self.gridLayout.addWidget(self.subject_comboBox, 2, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(teacher_add_form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.level_combobox = QtWidgets.QComboBox(teacher_add_form)
        self.level_combobox.setObjectName("level_combobox")
        self.gridLayout.addWidget(self.level_combobox, 3, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(teacher_add_form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.phone_input = QtWidgets.QLineEdit(teacher_add_form)
        self.phone_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.phone_input.setObjectName("phone_input")
        self.gridLayout.addWidget(self.phone_input, 4, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(teacher_add_form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.email_input = QtWidgets.QLineEdit(teacher_add_form)
        self.email_input.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.email_input.setObjectName("email_input")
        self.gridLayout.addWidget(self.email_input, 5, 1, 1, 2)
        self.add_button = QtWidgets.QPushButton(teacher_add_form)
        self.add_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon)
        self.add_button.setIconSize(QtCore.QSize(30, 30))
        self.add_button.setObjectName("add_button")
        self.gridLayout.addWidget(self.add_button, 6, 1, 1, 1)
        self.Cancel_button = QtWidgets.QPushButton(teacher_add_form)
        self.Cancel_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cancel_button.setIcon(icon1)
        self.Cancel_button.setIconSize(QtCore.QSize(30, 30))
        self.Cancel_button.setObjectName("Cancel_button")
        self.gridLayout.addWidget(self.Cancel_button, 6, 2, 1, 1)

        self.retranslateUi(teacher_add_form)
        QtCore.QMetaObject.connectSlotsByName(teacher_add_form)

    def retranslateUi(self, teacher_add_form):
        _translate = QtCore.QCoreApplication.translate
        teacher_add_form.setWindowTitle(_translate("teacher_add_form", "Form"))
        self.label.setText(_translate("teacher_add_form", "First name:"))
        self.label_2.setText(_translate("teacher_add_form", "Last name:"))
        self.label_3.setText(_translate("teacher_add_form", "Subject:"))
        self.label_4.setText(_translate("teacher_add_form", "Level:"))
        self.label_6.setText(_translate("teacher_add_form", "Phone:"))
        self.label_5.setText(_translate("teacher_add_form", "Email:"))
        self.add_button.setText(_translate("teacher_add_form", " Add"))
        self.Cancel_button.setText(_translate("teacher_add_form", " Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    teacher_add_form = QtWidgets.QWidget()
    ui = Ui_teacher_add_form()
    ui.setupUi(teacher_add_form)
    teacher_add_form.show()
    sys.exit(app.exec_())
