# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/teacher_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TeacherCard(object):
    def setupUi(self, TeacherCard):
        TeacherCard.setObjectName("TeacherCard")
        TeacherCard.resize(881, 901)
        TeacherCard.setStyleSheet("background-color:rgb(36, 31, 49);\n"
"color:white;\n"
"font-size:15px;\n"
"font-family: \"Century Gothic\";\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(TeacherCard)
        self.gridLayout.setObjectName("gridLayout")
        self.tabs = QtWidgets.QTabWidget(TeacherCard)
        self.tabs.setStyleSheet("\n"
"QTabWidget {\n"
"    background-color: rgb(70, 34, 67); /* Set the background color of the tab widget */\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: ; /* Set the text color of the tab */\n"
"    padding: 8px 12px;\n"
"    background-color: rgb(119, 118, 123);\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(222, 221, 218); /* Set the background color of the selected tab */\n"
"    color: rgb(0, 0, 0); /* Set the text color of the selected tab */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0)\n"
"}\n"
"\n"
"")
        self.tabs.setIconSize(QtCore.QSize(30, 30))
        self.tabs.setObjectName("tabs")
        self.info_tab = QtWidgets.QWidget()
        self.info_tab.setObjectName("info_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.info_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.info_stacked_widget = QtWidgets.QStackedWidget(self.info_tab)
        self.info_stacked_widget.setStyleSheet("")
        self.info_stacked_widget.setObjectName("info_stacked_widget")
        self.info_widget = QtWidgets.QWidget()
        self.info_widget.setObjectName("info_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.info_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.info_widget)
        self.widget.setStyleSheet("background-color:rgb(94, 92, 100)")
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labels_layout = QtWidgets.QVBoxLayout()
        self.labels_layout.setObjectName("labels_layout")
        self.gridLayout_4.addLayout(self.labels_layout, 0, 0, 1, 1)
        self.info_layout = QtWidgets.QVBoxLayout()
        self.info_layout.setObjectName("info_layout")
        self.gridLayout_4.addLayout(self.info_layout, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.info_widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.info_widget)
        self.tableView.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(8, 8, 8);")
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(270)
        self.gridLayout_3.addWidget(self.tableView, 3, 0, 2, 4)
        self.label = QtWidgets.QLabel(self.info_widget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 2)
        self.payement_button = QtWidgets.QPushButton(self.info_widget)
        self.payement_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/payment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.payement_button.setIcon(icon)
        self.payement_button.setIconSize(QtCore.QSize(30, 30))
        self.payement_button.setObjectName("payement_button")
        self.gridLayout_3.addWidget(self.payement_button, 5, 3, 1, 1)
        self.info_stacked_widget.addWidget(self.info_widget)
        self.payement_widget = QtWidgets.QWidget()
        self.payement_widget.setObjectName("payement_widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.payement_widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.teacher_payement_tableview = QtWidgets.QTableView(self.payement_widget)
        self.teacher_payement_tableview.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.teacher_payement_tableview.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.teacher_payement_tableview.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.teacher_payement_tableview.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.teacher_payement_tableview.setObjectName("teacher_payement_tableview")
        self.teacher_payement_tableview.horizontalHeader().setDefaultSectionSize(200)
        self.teacher_payement_tableview.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_5.addWidget(self.teacher_payement_tableview, 0, 0, 1, 2)
        self.return_button = QtWidgets.QPushButton(self.payement_widget)
        self.return_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.return_button.setIcon(icon1)
        self.return_button.setIconSize(QtCore.QSize(30, 30))
        self.return_button.setObjectName("return_button")
        self.gridLayout_5.addWidget(self.return_button, 3, 1, 1, 1)
        self.bill_button = QtWidgets.QPushButton(self.payement_widget)
        self.bill_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/add_records.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bill_button.setIcon(icon2)
        self.bill_button.setIconSize(QtCore.QSize(30, 30))
        self.bill_button.setObjectName("bill_button")
        self.gridLayout_5.addWidget(self.bill_button, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.payement_widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 1, 0, 1, 1)
        self.total_label = QtWidgets.QLabel(self.payement_widget)
        self.total_label.setText("")
        self.total_label.setObjectName("total_label")
        self.gridLayout_5.addWidget(self.total_label, 1, 1, 1, 1)
        self.generate_bill_checkbox = QtWidgets.QCheckBox(self.payement_widget)
        self.generate_bill_checkbox.setChecked(True)
        self.generate_bill_checkbox.setObjectName("generate_bill_checkbox")
        self.gridLayout_5.addWidget(self.generate_bill_checkbox, 2, 0, 1, 1)
        self.info_stacked_widget.addWidget(self.payement_widget)
        self.gridLayout_2.addWidget(self.info_stacked_widget, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabs.addTab(self.info_tab, icon3, "")
        self.gridLayout.addWidget(self.tabs, 0, 0, 1, 1)

        self.retranslateUi(TeacherCard)
        self.tabs.setCurrentIndex(0)
        self.info_stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TeacherCard)

    def retranslateUi(self, TeacherCard):
        _translate = QtCore.QCoreApplication.translate
        TeacherCard.setWindowTitle(_translate("TeacherCard", "Form"))
        self.label_2.setText(_translate("TeacherCard", "Classes:"))
        self.label.setText(_translate("TeacherCard", "Teacher Info:"))
        self.payement_button.setText(_translate("TeacherCard", " Payement"))
        self.return_button.setText(_translate("TeacherCard", " Return"))
        self.bill_button.setText(_translate("TeacherCard", " add payment"))
        self.label_3.setText(_translate("TeacherCard", "Total salary this month:"))
        self.generate_bill_checkbox.setText(_translate("TeacherCard", "generate bill"))
        self.tabs.setTabText(self.tabs.indexOf(self.info_tab), _translate("TeacherCard", "Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TeacherCard = QtWidgets.QWidget()
    ui = Ui_TeacherCard()
    ui.setupUi(TeacherCard)
    TeacherCard.show()
    sys.exit(app.exec_())
