# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/time_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_time_management(object):
    def setupUi(self, time_management):
        time_management.setObjectName("time_management")
        time_management.resize(1644, 875)
        time_management.setStyleSheet("background-color: rgb(61, 56, 70);\n"
"color: rgb(255, 255, 255);\n"
"font-family: \"Century Gothic\";\n"
"font-size:15px")
        self.tableView = QtWidgets.QTableView(time_management)
        self.tableView.setGeometry(QtCore.QRect(0, 10, 1641, 851))
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(200)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.verticalHeader().setDefaultSectionSize(100)

        self.retranslateUi(time_management)
        QtCore.QMetaObject.connectSlotsByName(time_management)

    def retranslateUi(self, time_management):
        _translate = QtCore.QCoreApplication.translate
        time_management.setWindowTitle(_translate("time_management", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    time_management = QtWidgets.QWidget()
    ui = Ui_time_management()
    ui.setupUi(time_management)
    time_management.show()
    sys.exit(app.exec_())
