# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui/user_add_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_user_form(object):
    def setupUi(self, add_user_form):
        add_user_form.setObjectName("add_user_form")
        add_user_form.resize(722, 676)
        add_user_form.setStyleSheet("background-color: rgb(61, 56, 70);\n"
"color: rgb(255, 255, 255);\n"
"font-family: \"Century Gothic\";\n"
"font-size:15px")
        self.gridLayout = QtWidgets.QGridLayout(add_user_form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(add_user_form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(add_user_form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(add_user_form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.add_button = QtWidgets.QPushButton(add_user_form)
        self.add_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon)
        self.add_button.setIconSize(QtCore.QSize(30, 30))
        self.add_button.setObjectName("add_button")
        self.gridLayout.addWidget(self.add_button, 4, 3, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(add_user_form)
        self.cancel_button.setStyleSheet("QPushButton {\n"
"    background-color:rgb(61, 56, 70);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(119, 118, 123);  /* Change the hover color as desired */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(192, 191, 188);  /* Change the pressed color as desired */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(222, 221, 218); /* Change the disabled color as desired */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_button.setIcon(icon1)
        self.cancel_button.setIconSize(QtCore.QSize(30, 30))
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 4, 4, 1, 1)
        self.role_comboBox = QtWidgets.QComboBox(add_user_form)
        self.role_comboBox.setObjectName("role_comboBox")
        self.gridLayout.addWidget(self.role_comboBox, 3, 3, 1, 2)
        self.password_input_2 = QtWidgets.QLineEdit(add_user_form)
        self.password_input_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input_2.setObjectName("password_input_2")
        self.gridLayout.addWidget(self.password_input_2, 2, 3, 1, 2)
        self.password_input = QtWidgets.QLineEdit(add_user_form)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.gridLayout.addWidget(self.password_input, 1, 3, 1, 2)
        self.username_input = QtWidgets.QLineEdit(add_user_form)
        self.username_input.setObjectName("username_input")
        self.gridLayout.addWidget(self.username_input, 0, 3, 1, 2)
        self.label_4 = QtWidgets.QLabel(add_user_form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)

        self.retranslateUi(add_user_form)
        QtCore.QMetaObject.connectSlotsByName(add_user_form)

    def retranslateUi(self, add_user_form):
        _translate = QtCore.QCoreApplication.translate
        add_user_form.setWindowTitle(_translate("add_user_form", "Form"))
        self.label.setText(_translate("add_user_form", "Username:"))
        self.label_2.setText(_translate("add_user_form", "Role:"))
        self.label_3.setText(_translate("add_user_form", "Password:"))
        self.add_button.setText(_translate("add_user_form", " Add"))
        self.cancel_button.setText(_translate("add_user_form", " Cancel"))
        self.label_4.setText(_translate("add_user_form", "confirm Password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_user_form = QtWidgets.QWidget()
    ui = Ui_add_user_form()
    ui.setupUi(add_user_form)
    add_user_form.show()
    sys.exit(app.exec_())
